## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux

julia:
  - 0.7
  - 1.0

env:
  - CONDA_JL_VERSION="3" PYTHON=""

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - python3-dev
    - clang-3.9


notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to override the default test script
script:
  - git clone https://github.com/JuliaRegistries/General  $(julia -e 'import Pkg; println(joinpath(Pkg.depots1(), "registries", "General"))')    
  - git clone https://github.com/JuliaPOMDP/Registry  $(julia -e 'import Pkg; println(joinpath(Pkg.depots1(), "registries", "JuliaPOMDP"))')  
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --project --color=yes -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/sisl/Spot.jl.git"))'
  - julia --project --color=yes -e 'import Pkg; Pkg.build(); Pkg.test(coverage=true)'
after_success:
  - julia --project -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia --project -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'